language: node_js
node_js:
  - "10.16.0"
install:
  - npm i
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script:
        # Lint all
        - npm run lint
    - stage: test
      script:
        - npm run bootstrap
        - npm run test
